### ISSUE TITLE
warning: react-native-ytdl is out of date, even though installed@latest  (yarn add react-native-ytdl@latest)

### ISSUE THREAD

**Issue by edo92** [ytdl-js/react-native-ytdl#64]
WARNING: react-native-ytdl is out of date! If the latest port is available, update with "npm install react-native-ytdl@latest".
throws warning even though is install react-native-ytdl@latest

**Comment by AbelTesfaye** [comment]
Fixed. Run `npm i react-native-ytdl@latest` in your project root folder to remove the warning

**Comment by edo92** [comment]
I have deleted node_modules and  tried npm i react-native-ytdl@latest but  still throwing warning. Is there any way to silence the warning from the module ?

**Comment by edo92** [comment]
I think the problem comes from utiles.js file where tag_name is not matching with the current version

`   
 if (JSON.parse(response).tag_name !== `v${pkg.version}`) {
      console.warn("\u001b[33mWARNING:\u001b[0m react-native-ytdl is out of date! If the latest port is available, update with \"npm install react-native-ytdl@latest\".");
}
`

when i run npm install react-native-ytdl@latest it installs v4.2.1
but in JSON.parse(response).tag_name it is v4.4.0 
that is why it always throws this warning

**Comment by OmarSaidIbrahim** [comment]
Hi guys, is there any news about this ?
I still get the warning
