### ISSUE TITLE
 react-native-ytdl is out of date! 

### ISSUE THREAD

**Issue by ikbal99** [ytdl-js/react-native-ytdl#85]
react-native-ytdl is out of date! If the latest port is available, update with "npm install react-native-ytdl@latest".

i have upated more than 6 times same issue

**Comment by react-native-ytdl** [comment]
Should be fixed now

**Comment by eulerkochy** [comment]
Hi, I am still getting this error in my react-native application(Android), on running the `4.8.3` build. I have installed using `npm i react-native-ytdl@latest`. This package was working fine a week back, how can I revert to the older build?
